### PR TITLE
Fix Four Finger Tap Sound

### PR DESCRIPTION
**Pull request by Lucien950**

### CODE REVIEW

**Comment by Lucien950** [comment]
Closes #200

**Comment by Lucien950** [comment]
fixes #200

**Comment by AspectOfJerry** [comment]
I believe that this also fixes #193. 👍

**Comment by Lucien950** [comment]
> I believe that this also fixes #193. 👍
> 
> Edit: I also just realized that you created both issues. 😅

yeah my B I didn't realize

**Review by AspectOfJerry — APPROVED** [review]

**Comment by Lucien950** [comment]
Can we get a merge?

**Comment by Lucien950** [comment]
TODO: for this branch to merge, meta keys cannot all be suppressed, as windows key is also a meta key. perhaps only meta keys with function keys not on the keyboard (f13+) should be suppressed.

**Pull request closed without merging**
