### PR TITLE
Added dark mode support with a checkbox

### PR DESCRIPTION
**Pull request by karimk123**
I added a checkbox with for enabling and disabling dark mode and added the functionality. Of course, dark colors, position of the checkbox can all be improved but focused more on the functionality itself and hopefully its gets accepted.

### CODE REVIEW

**Comment by max-programming** [comment]
Can you show a screenshot of how it looks now? @karimk123

**Comment by karimk123** [comment]
> Can you show a screenshot of how it looks now? @karimk123 

I dont have my laptop on me right now, could you please try it on your end and see how it looks like?

**Comment by max-programming** [comment]
> > Can you show a screenshot of how it looks now? @karimk123
> 
> I dont have my laptop on me right now, could you please try it on your end and see how it looks like?

Sadly I don't have Linux on my machine. Share it whenever you can

**Comment by max-programming** [comment]
> > Can you show a screenshot of how it looks now? @karimk123
> 
> I dont have my laptop on me right now, could you please try it on your end and see how it looks like?

Ok I'll try

**Comment by karimk123** [comment]
What do you think?

**Comment by iammursalin** [comment]
> What do you think?

Where are the screenshots? I would like to see it. Please add some.

**Comment by NotLazy** [comment]
It doesn't look like this does anything in terms of storing the setting, so everytime the app restarts your choice will reset to default. I might re-implement this using the new checkbox CSS I added in #247

**Pull request closed without merging**
