### PR TITLE
Introduce config versions and implement config v2

### PR DESCRIPTION
**Pull request by withinboredom**
This addresses #21 by attempting to play `{keycode}-up` on keyup. It appears to work really well when there is already a gap in the recording between key-up and key-down. I've added updated a few keys in one of the built-in soundpacks, but it is a pretty tedious undertaking.

I don't want to continue on this if there isn't an interest in it or if it has no chance of being merged. This solution seems rather simplistic, but appears to work somewhat brilliantly.

### CODE REVIEW

**Comment by NotLazy** [comment]
Unfortunately, this won't be merged due to our plans to release new config versions, either in the next version or the version after at the latest.

See: #38 #268

**Comment by NotLazy** [comment]
I did try to release the schematics for the new config versions on the wiki, but we received too many complaints about "incomplete or wrong information on the wiki" for it to stay there. 

If you'd like to assist us with implementing config v3, here's the demo:

```javascript
{
	"sounds": {
		// play a clip of the file
		"keydown": {
			"file": "#/sound.ogg", // #/ marks the root of the soundpack
			"clip": [2186, 281], // ["start", "length"]
		},
		"keyup": {
			"file": "#/sound.ogg",
			"clip": [3251, 281],

			// note that this is the default, and you don't need to specify it. See below for when you would want to define mode.
			"mode": "default"
		},

		// play the whole file
		"key_down": {
			"file": "#/sound2.ogg",
		},
		"key_up": {
			"file": "#/sound2_up.ogg",
		},

		// if the key is held, repeat after x ms
		"key_repeat": {
			"file": "#/sound3.ogg",
			"repeat-delay": 1000 // 1s
		},
		"repeatkey": {
			"file": "#/sound.ogg",
			"clip": [4566, 191],
			"repeat-delay": 2500 // 2.5s
		},

		// cycle through random sounds
		"keyrandom": {
			"mode": "random",
			"file": "#/sound.ogg",
			"clips": [
				[1321, 191],
				[1542, 191],
			]
		},
		"key_random": {
			"mode": "random",
			"files": [
				"#/sound2.ogg",
				"#/sound3.ogg"
			]
		},
		"key_random_repeat": {
			"mode": "random",
			"files": [
				"#/sound2.ogg",
				"#/sound3.ogg",
			],
			"repeat-delay": 1500, // 1.5s
		},

		// cycle through each file in order
		"key_cycle": {
			"mode": "cycle",
			"files": [
				"#/duck.ogg",
				"#/duck.ogg",
				"#/goose.ogg",
			]
		}
		// cycle through each clip in order
		"keycycle": {
			"mode": "cycle",
			"clips": [
				[1321, 191],
				[1542, 191],
			]
		}
	}

	// key definitions
	"defines": {
		// format
		"keyCode": ["keyDown", "keyUp"]
		// definitions

		// define one sound for key down only
		"1": ["keydown"],

		// define two sounds for key down and key up
		"2": ["key_down", "keyup"],

		// repeating keys must be on the keydown cycle
		"3": ["key_repeat"],

		// cycling keys must be on the keydown cycle, but they must also have multiple definitions to function.
		"4": ["key_cycle"],
		"5": ["key_cycle"],
	},

	// this is required.
	"version": 3

	// v3 standardizes metadata storage.
	"metadata": {}
}
```

**Comment by withinboredom** [comment]
Ah bummer @NotLazy, just saw this :)

I ended up making some config changes to support a bit simpler stuff as well.

Here's my changes to the existing config:

```json5
{
  "id": "custom-sound-pack-1720300926819",
  "name": "pandas",
  "key_define_type": "multi",
  "includes_numpad": false,
  "sound": "GENERIC_R{0-4}.mp3", // pick a random sound from 0-4, if a keydown isn't defined
  "soundup": "release/GENERIC.mp3", // play this if an up isn't defined
  "defines": {
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": "BACKSPACE.mp3", // can also be something like BACKSPACE{0-10}.mp3
    "14-up": "release/BACKSPACE.mp3"
    // etc
}
```

Your new config format looks quite comprehensive, but if I could make a suggestion, just have two define keys: 

```json
{
  "sounds": {},
  "defines": {
    "keydown": {},
    "keyup": {},
  }
}
```

one for key down sounds and one for key up sounds. Then, later -- or now -- you can add different things like `"keyhold"` and such.

**Comment by NotLazy** [comment]
I see the vibe you're trying to go with, with your suggestion, but it's sort of opposite of what we're trying to do with the new config version. I'm not opposed to holding a vote internally with the rest of the team though, so I might just do that and get back to you.

Ultimately the fact of the matter is that sound pack authors shouldn't need to edit config.json manually in the future as we're building an editor on our website which aims to maximize user friendliness, and handle every potential configuration for you.

**Comment by NotLazy** [comment]
@withinboredom It's been decided that the config v2 draft will be modified to match whatever config changes you write into this PR, and that unless you want to work on v3, you can continue work on this version, and it will be added as config v2 in the next release.

**Comment by withinboredom** [comment]
I've added my changes. Most notable are the following:

- removed an app.exit on volume error, as this was triggering on windows but the comment was correct on linux
- added a new pack (to make it easy to test; dunno if the right to distribute the audio is included in the license from https://github.com/tplai/kbsim)
- for `multi` key defines:
  - `sound` is the default if the keycode define is `null`
  - `soundup` is the default up-sound if the keycode up is `null` or `undefined`
  - an up-sound can be specified by adding `-up` to the keycode
  - a random sound can be applied by naming a sound file with numerics and specifying the range in the filename in the config. e.g., `SOUND{1-5}.wav` will select `SOUND1.wav`, `SOUND2.wav`, etc.

I believe the v3 config example you gave will be much more flexible, but this can at least get people working on keydown/up packs so that by the time v3 launches, there'll be plenty of content.

> it's sort of opposite of what we're trying to do with the new config version.

I just saw that that the config required a convention: `"2": ["key_down", "keyup"],` which I assume is that `[0]` is keydown sound and `[1]` is keyup sound. If you wanted to add a 'keyrepeat' or 'keyhold' sound, for example, it would get weird when you wanted _only_ a `keyrepeat` sound: `"2": [null, null, "lasers"],` as you'd have to check for two things:

1. that the index exists
2. it isn't null

I was just trying to suggest something that would be easier to load into internal configuration.

```
if config.keydown[keycode]:
  // configure keydown sounds

if config.keyup[keycode]:
  // configure keyup sounds

if config.keyhold[keycode]:
  // configure keyhold sounds
```

> Ultimately the fact of the matter is that sound pack authors shouldn't need to edit config.json manually

I don't think my suggestion precludes that, as I suspect the editor's internal configuration will be vastly different than whatever is stored on disk.

> unless you want to work on v3

I don't see a v3 branch, but sure, if I can help out as time allows, I'd love to check it out.

**Comment by NotLazy** [comment]
I went ahead and used your PR to add support for more config versions, and made your config changes official as config v2, as well as updating the internal v2 draft. I also used this time to improve soundpack loading, so less is done to soundpacks during initialization and more is done when actually loading the packs. 

I also updated the soundpack example provided to not only optimize the config, but also remove the deprecated "includes_numpad" key, since v2 and above were already planned to not include it. Honestly, now that I think about it I'm not sure why I didn't just completely remove it from v1 during these changes, since it's completely unused (before and after), but whatever. it stays I guess.

**Comment by NotLazy** [comment]
> I just saw that that the config required a convention: `"2": ["key_down", "keyup"],` which I assume is that `[0]` is keydown sound and `[1]` is keyup sound. If you wanted to add a 'keyrepeat' or 'keyhold' sound, for example, it would get weird when you wanted _only_ a `keyrepeat` sound: `"2": [null, null, "lasers"],`

As you can see in the example I provided, the definitions for 3 4 and 5 set the precedence on how random and cycling keys work. They do not make use of "key_up" events or make use of a 3rd index, but rather are only supported on "key_down" events. Though, in theory, there's no reason that random can't be supported for "key_up" events as well, so the only sound mode which wouldn't be supported on the "key_up" event would be cycling sounds.

It's important to keep in mind that in config v3, settings are established on a per-sound basis, not a per-key basis. So you'll name sounds, eg. "backspace_down" or "backspace_up" or "backspace_random", though the name really doesn't matter and is just for your reference. Then, when defining keys, you use the sound names, instead of the sound paths.

This convention saves on config sizes when configuring complicated logic for how sounds should operate, by allowing you to do this:
```javascript
{
	"sounds": {
		"repeat": {
			"mode": "random",
			"files": [
				"#/sound1.ogg",
				"#/sound3.ogg",
				"#/sound4.ogg"
			],
			"repeat-delay": 1500, // 1.5s
			"reroll": false // don't reroll on repeat
		}
	}

	"defines": {
		"1": ["repeat"],
		"2": ["repeat"],
		"3": ["repeat"],
		// ...
	}
}
```

instead of this:
```javasciprt
{
	"defines": {
		"1": {
			"mode": "random",
			"files": [
				"#/sound1.ogg",
				"#/sound3.ogg",
				"#/sound4.ogg"
			],
			"repeat-delay": 1500, // 1.5s
			"reroll": false // don't reroll on repeat
		},
		"2": {
			"mode": "random",
			"files": [
				"#/sound1.ogg",
				"#/sound3.ogg",
				"#/sound4.ogg"
			],
			"repeat-delay": 1500, // 1.5s
			"reroll": false // don't reroll on repeat
		},
		"3": {
			"mode": "random",
			"files": [
				"#/sound1.ogg",
				"#/sound3.ogg",
				"#/sound4.ogg"
			],
			"repeat-delay": 1500, // 1.5s
			"reroll": false // don't reroll on repeat
		}
		// ...
	}
}
```

I mention this because, by doing it this way, it's as simple as adding new sound modes, to support new actions, instead of adding a new key `{"defines":{"keydown":..., "keyup":..., "keyhold":..., "keycycle":...}`

Some things about v3 I haven't mentioned or included in the demo config yet, is the reserved keywords for definitions, such as "default" which does what you're doing in v2's "multi" key definition mode with "sound" and "soundup"

**Comment by khaledbombark-maker** [comment]
K

**Comment by khaledbombark-maker** [comment]
D

**Pull request merged**
